// Appraisal Report Data — 4067 E 518 N, Rigby, ID 83442
// File No: JDGP2604DOE | Effective Date: 04/22/2026
// Client: Jane Doehead | Appraiser: Lowball Joe | Company: Peak Value Appraisals

export const reportData = {
  // ── Report Meta ──────────────────────────────────────────────────────────
  fileNo: "JDGP2604DOE",
  effectiveDate: "April 22, 2026",
  reportDate: "April 24, 2026",
  deliveryDate: "April 28, 2026",
  expirationDate: new Date("2026-07-22"), // 90 days from effective date
  password: "PEAK2026",

  // ── Subject Property ─────────────────────────────────────────────────────
  subject: {
    address: "4067 E 518 N",
    city: "Rigby",
    state: "ID",
    zip: "83442",
    county: "Jefferson",
    legalDescription: "LOT 16 BLK 1 PONDEROSA ESTATES DIV #1 SEC 5 TWP 4 NORTH RGE 39 EBM",
    parcelNumber: "RP005980010160",
    taxYear: "2025",
    annualTaxes: 1230,
    currentOwner: "Stingy Jack",
    occupancy: "Owner",
    propertyRights: "Fee Simple",
    zoning: "R-1 Residential Use with mixed Other Uses allowed",
    zoningCompliance: "Legal",
    lat: 43.7621,
    lng: -111.9085,
  },

  // ── Property Details ─────────────────────────────────────────────────────
  improvements: {
    style: "Ranch",
    yearBuilt: 2009,
    effectiveAge: 9,
    actualAge: 17,
    stories: 1,
    grossLivingArea: 1732,
    basementArea: 1732,
    basementFinished: 1732,
    garageArea: 902,
    garageType: "3-car attached",
    totalRooms: 6,
    bedrooms: 3,
    bathrooms: "2.1",
    foundation: "Concrete",
    exteriorWalls: "Stone, Vinyl",
    roofSurface: "Composite Shingle",
    heating: "FWA / Gas",
    cooling: "Central AC",
    condition: "C2 (Good)",
    quality: "Q3",
    additionalFeatures: "Vaulted ceilings, granite countertops, custom cabinets, stainless steel appliances",
    amenities: ["Fireplace (1)", "Sprinkler System", "Patio", "Covered Porch", "3-car Garage"],
    utilities: {
      water: "Private Well",
      sewer: "Private Septic",
      gas: "Yes",
      electricity: "Yes",
    },
    floodZone: "X",
    floodMapNo: "16051C1634C",
    floodMapDate: "9/26/2008",
  },

  // ── Site ─────────────────────────────────────────────────────────────────
  site: {
    siteArea: "1.01 acres",
    siteAreaSF: 44000,
    shape: "Generally Level",
    topography: "Level",
    street: "Paved",
    view: "N;Res;",
    drainage: "Adequate",
    utilities: "Private Well, Private Septic, Gas",
    offSiteImprovements: "Paved street typical for area",
    insideLot: true,
  },

  // ── Neighborhood ─────────────────────────────────────────────────────────
  neighborhood: {
    location: "Rural",
    builtUp: "10–25%",
    growthRate: "Stable",
    propertyValues: "Stable",
    demandSupply: "In Balance",
    marketingTime: "3–6 Months",
    boundaries: {
      north: "HWY 20",
      south: "500 N",
      east: "Lewis Lane",
      west: "Highway 20",
    },
    oneUnitPct: 80,
      commercialPct: 5,
    vacantPct: 10,
    otherPct: 5,
    priceRange: { low: 400000, high: 800000, predominant: 664000 },
    ageRange: { low: 3, high: 12, predominant: 9 },
    description: "The subject's neighborhood is bounded by HWY 20 to the North, 500 N to the South, Lewis Lane to the East, and Highway 20 to the West. Building prices are typically higher than existing home prices and there is an average amount of new construction going on right now. Financing is available from a number of sources (including FHA and other government programs). Interest rates are reasonably high at present and a variety of loan options are available.",
  },

  // ── Final Value ──────────────────────────────────────────────────────────
  finalValue: 664000,
  valueApproach: "Sales Comparison Approach (primary), Cost Approach (secondary)",
  salesCompValue: 664000,
  costApproachValue: 679183,

  // ── Sales Comparison ─────────────────────────────────────────────────────
  comparables: [
    {
      id: 1,
      address: "3689 E 20 N",
      city: "Rigby, ID 83442",
      proximity: "6.30 miles SW",
      salePrice: 660000,
      salePricePerSF: 367.28,
      saleDate: "01/30/2026",
      daysOnMarket: 82,
      mlsNumber: "2180104",
      financing: "Conv",
      concessions: 0,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "27,878 sf",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q3",
      age: 5,
      condition: "C2",
      rooms: 6, bedrooms: 3, bathrooms: "2.0",
      gla: 1797,
      basement: "1,797 sf finished",
      garage: "3-car, 3-dw",
      porch: "Patio, Covered Porch",
      fireplace: 1,
      sprinkler: true,
      adjustments: {
        concessions: 0,
        time: 0,
        location: 0,
        site: 2500,
        view: 0,
        quality: 0,
        age: 0,
        condition: 0,
        rooms: -5000,
        gla: -3300,
        basement: 0,
        garage: 0,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: -5800,
      adjustedPrice: 654200,
    },
    {
      id: 2,
      address: "3839 E 120 N",
      city: "Rigby, ID 83442",
      proximity: "4.65 miles SW",
      salePrice: 660000,
      salePricePerSF: 363.24,
      saleDate: "11/21/2025",
      daysOnMarket: 157,
      mlsNumber: "2176654",
      financing: "Conv",
      concessions: 0,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "1 ac / 27,007 sf",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q3",
      age: 8,
      condition: "C2",
      rooms: 5, bedrooms: 2, bathrooms: "1.1",
      gla: 1817,
      basement: "1,817 sf finished",
      garage: "3-car, 4-dw",
      porch: "Covered Patio, Covered Porch",
      fireplace: 2,
      sprinkler: true,
      adjustments: {
        concessions: 0,
        time: 0,
        location: 0,
        site: 2500,
        view: 0,
        quality: 0,
        age: 0,
        condition: 0,
        rooms: -5000,
        gla: -4300,
        basement: 0,
        garage: -10000,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: 700,
      adjustedPrice: 660700,
    },
    {
      id: 3,
      address: "17 N 3928 E",
      city: "Rigby, ID 83442",
      proximity: "5.24 miles SW",
      salePrice: 674900,
      salePricePerSF: 357.66,
      saleDate: "10/28/2025",
      daysOnMarket: 17,
      mlsNumber: "2179515",
      financing: "VA",
      concessions: 0,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "1.01 ac",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q3",
      age: 9,
      condition: "C2",
      rooms: 5, bedrooms: 2, bathrooms: "2.0",
      gla: 1887,
      basement: "1,887 sf finished",
      garage: "3-car, 3-dw",
      porch: "Covered Patio, Covered Porch",
      fireplace: 1,
      sprinkler: true,
      adjustments: {
        concessions: 0,
        time: 0,
        location: 0,
        site: 5000,
        view: 0,
        quality: 0,
        age: 0,
        condition: 0,
        rooms: -5000,
        gla: -7800,
        basement: 0,
        garage: 0,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: -8100,
      adjustedPrice: 666800,
    },
    {
      id: 4,
      address: "3672 E 20 N",
      city: "Rigby, ID 83442",
      proximity: "6.43 miles SW",
      salePrice: 678000,
      salePricePerSF: 349.85,
      saleDate: "09/19/2025",
      daysOnMarket: 110,
      mlsNumber: "2176405",
      financing: "VA",
      concessions: -20340,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "26,572 sf",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q3",
      age: 4,
      condition: "C2",
      rooms: 6, bedrooms: 3, bathrooms: "2.1",
      gla: 1938,
      basement: "1,628 sf finished",
      garage: "3-car, 4-dw",
      porch: "Patio, Covered Porch",
      fireplace: 1,
      sprinkler: true,
      adjustments: {
        concessions: -20340,
        time: 0,
        location: 0,
        site: 2500,
        view: 0,
        quality: 0,
        age: 0,
        condition: 0,
        rooms: 0,
        gla: -10300,
        basement: 5200,
        garage: -10000,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: 4260,
      adjustedPrice: 682260,
    },
    {
      id: 5,
      address: "312 N 3811 E",
      city: "Rigby, ID 83442",
      proximity: "3.32 miles SW",
      salePrice: 625000,
      salePricePerSF: 354.31,
      saleDate: "08/20/2025",
      daysOnMarket: 84,
      mlsNumber: "2176355",
      financing: "Conv",
      concessions: -3000,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "21,780 sf",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q4",
      age: 6,
      condition: "C2",
      rooms: 5, bedrooms: 3, bathrooms: "2.0",
      gla: 1764,
      basement: "1,764 sf finished",
      garage: "2-car, 3-dw",
      porch: "Multi",
      fireplace: 2,
      sprinkler: true,
      adjustments: {
        concessions: -3000,
        time: 0,
        location: 0,
        site: 0,
        view: 0,
        quality: 34700,
        age: 0,
        condition: 0,
        rooms: -5000,
        gla: 0,
        basement: 0,
        garage: 10000,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: 39800,
      adjustedPrice: 664800,
    },
    {
      id: 6,
      address: "3703 E 337 N",
      city: "Rigby, ID 83442",
      proximity: "4.10 miles SW",
      salePrice: 655000,
      salePricePerSF: 388.95,
      saleDate: "Active Listing",
      daysOnMarket: 308,
      mlsNumber: "2177632",
      financing: "Listing",
      concessions: 0,
      propertyRights: "Fee Simple",
      location: "N;Res;",
      siteArea: "1.03 ac",
      view: "N;Res;",
      style: "Ranch",
      quality: "Q4",
      age: 6,
      condition: "C2",
      rooms: 6, bedrooms: 3, bathrooms: "2.1",
      gla: 1684,
      basement: "1,684 sf finished",
      garage: "3-car, 3-dw",
      porch: "Multi",
      fireplace: 1,
      sprinkler: true,
      adjustments: {
        concessions: 0,
        time: 0,
        location: 0,
        site: 0,
        view: 0,
        quality: 33680,
        age: 0,
        condition: 0,
        rooms: -10000,
        gla: 0,
        basement: 0,
        garage: 0,
        porch: 0,
        fireplace: 0,
        other: 0,
      },
      netAdjustment: 23680,
      adjustedPrice: 678680,
    },
  ],

  // ── Cost Approach ─────────────────────────────────────────────────────────
  costApproach: {
    siteValue: 97000,
    sourceOfCostData: "DwellingCost.com",
    effectiveDateOfCostData: "April 7, 2026",
    qualityRating: "7.0",
    dwelling: { sqft: 1732, ratePerSF: 212.07, total: 367305 },
    basement: { sqft: 1732, ratePerSF: 86.40, total: 149645 },
    garage: { sqft: 902, ratePerSF: 55.01, total: 49619 },
    otherAmenities: 15000,
    totalCostNew: 581569,
    physicalDepreciation: 19386,
    depreciatedCostOfImprovements: 562183,
    siteImprovements: 20000,
    indicatedValueByCostApproach: 679183,
    remainingEconomicLife: 58,
    // DwellingCost.com breakdown
    dwellingCostPerSF: 318.96,
    garageCostPerSF: 79.45,
    basementCostPerSF: 146.14,
    dwellingTotal: 552439,
    garageTotal: 71664,
    basementTotal: 253114,
  },

  // ── Market Analysis (from farm list) ─────────────────────────────────────
  marketData: {
    priorYear: { sales: 22, medianPrice: 625000, medianDOM: 82 },
    prior6Mo: { sales: 14, medianPrice: 645000, medianDOM: 75 },
    current3Mo: { sales: 8, medianPrice: 664000, medianDOM: 60 },
    trend: "Stable",
    supplyDemand: "In Balance",
    listToSaleRatio: 0.978,
    // Monthly price trend data for chart
    monthlyTrend: [
      { month: "Jul 2025", medianPrice: 620000, sales: 6, dom: 35 },
      { month: "Aug 2025", medianPrice: 625000, sales: 4, dom: 84 },
      { month: "Sep 2025", medianPrice: 640000, sales: 5, dom: 95 },
      { month: "Oct 2025", medianPrice: 635000, sales: 4, dom: 80 },
      { month: "Nov 2025", medianPrice: 650000, sales: 3, dom: 130 },
      { month: "Dec 2025", medianPrice: 645000, sales: 2, dom: 110 },
      { month: "Jan 2026", medianPrice: 655000, sales: 3, dom: 82 },
      { month: "Feb 2026", medianPrice: 660000, sales: 3, dom: 75 },
      { month: "Mar 2026", medianPrice: 665000, sales: 4, dom: 60 },
      { month: "Apr 2026", medianPrice: 664000, sales: 2, dom: 55 },
    ],
    // Price distribution from farm list
    priceDistribution: [
      { range: "$460K–$520K", count: 4 },
      { range: "$520K–$580K", count: 5 },
      { range: "$580K–$640K", count: 8 },
      { range: "$640K–$700K", count: 14 },
      { range: "$700K–$800K", count: 5 },
      { range: "$800K+", count: 1 },
    ],
  },

  // ── Engagement & Order ────────────────────────────────────────────────────
  engagement: {
    orderDate: "April 17, 2026",
    contactName: "Lowball Joe",
    appraisalCompany: "Peak Value Appraisals, LLC",
    phone: "(208) 701-6191",
    email: "service@peakvalueappraisals.com",
    clientName: "Jane Doehead",
    propertyAddress: "4067 E 518 N, Rigby, ID 83442",
    intendedUse: "To determine the current market value for pre-nuptial agreement purposes",
    valueType: "Market Value as defined in USPAP",
    fee: 900,
    paymentMethod: "Money Order",
    paymentDate: "April 22, 2026",
    paymentStatus: "Paid",
    paymentAmount: 900,
    inspectionDate: "April 22, 2026",
    inspectionWindow: "12PM – 4PM",
    deliveryEmail: "client.demo@example.com",
    deliveryMethod: "Email",
    orderConfirmed: true,
    confirmationDate: "April 17, 2026",
    invoiceNumber: "JDGP2604DOE",
    reportType: "General Purpose Appraisal Report (GPAR)",
    uspapCompliant: true,
  },

  // ── Appraiser Profile ─────────────────────────────────────────────────────
  appraiser: {
    name: "Lowball Joe",
    company: "Peak Value Appraisals",
    address: "328 N 4440 E, Rigby, ID 83442",
    phone: "(208) 701-6191",
    email: "service@peakvalueappraisals.com",
    website: "www.peakvalueappraisals.com",
    licenseNumber: "CRA-7731",
    licenseState: "ID",
    designation: "Certified Residential Appraiser",
    licenseExpiration: "09/15/2028",
    inspectionDate: "April 22, 2026",
    signatureDate: "April 24, 2026",
    yearsExperience: 30,
  },

  // ── FAQ ───────────────────────────────────────────────────────────────────
  faq: [
    {
      q: "Why is my property valued at $664,000?",
      a: "The final value of $664,000 was determined primarily through the Sales Comparison Approach, which analyzed six comparable sales in the Rigby market ranging from $625,000 to $682,260 after adjustments. The adjusted values clustered tightly between $654,200 and $682,260, with the final value representing a weighted reconciliation of these comparables. The Cost Approach independently indicated $679,183, providing additional support for this conclusion.",
    },
    {
      q: "What is the Sales Comparison Approach?",
      a: "The Sales Comparison Approach is the most widely used method for residential appraisals. The appraiser identifies recent sales of similar properties (comparables) in the same market area, then makes dollar adjustments for differences between each comparable and your property — such as size, condition, amenities, and location. The adjusted prices of the comparables bracket the subject's value, allowing the appraiser to form a well-supported opinion.",
    },
    {
      q: "What is the Cost Approach and why was it used?",
      a: "The Cost Approach estimates value by calculating what it would cost to replace the improvements (house, garage, basement) at today's construction costs, then subtracting depreciation, and adding the land value. For this property, the replacement cost new was estimated at $581,569 using DwellingCost.com data. After deducting $19,386 in physical depreciation and adding $97,000 in land value and $20,000 in site improvements, the indicated value was $679,183. This approach provided secondary support for the final value conclusion.",
    },
    {
      q: "What does 'effective age' mean vs. actual age?",
      a: "The actual age of the home is 17 years (built in 2009). However, the effective age is only 9 years, reflecting the property's excellent condition, quality construction, and well-maintained improvements. Effective age is the appraiser's estimate of how old the property appears to function, which directly affects the depreciation calculation in the Cost Approach.",
    },
    {
      q: "Why are some comparables more than a mile away?",
      a: "The subject is located in a limited rural market. In densely populated urban areas, comparables within a half-mile are common. In rural markets like Rigby, it is standard practice to expand the search radius to find the most similar properties, even if they are several miles away. The distances used in this report are not considered excessive given the nature of the market.",
    },
    {
      q: "Can I challenge the appraised value?",
      a: "Yes. If you believe the value is incorrect, you may submit a Reconsideration of Value (ROV) request to the appraiser. To be considered, you should provide specific comparable sales that you believe were overlooked, factual errors in the property description, or other verifiable data that may affect the value. General disagreement with the value without supporting data is not typically sufficient grounds for reconsideration.",
    },
    {
      q: "What is the intended use of this appraisal?",
      a: "This appraisal was ordered to determine the current market value of the property for pre-nuptial agreement purposes. The intended user is the client listed on the engagement letter. This report should not be used for mortgage lending, tax appeals, or any other purpose without the appraiser's written consent.",
    },
    {
      q: "How long is this appraisal valid?",
      a: "This interactive report is accessible for 90 days from the effective date of April 22, 2026. The appraisal itself reflects market conditions as of the effective date. Real estate markets change over time, so this value opinion may not accurately reflect market conditions after the effective date.",
    },
    {
      q: "What is a private well and septic system, and does it affect value?",
      a: "The subject property uses a private well for water supply and a private septic system for waste disposal, which is typical and standard for rural properties in the Rigby, Idaho market area. These systems do not adversely impact the property's marketability, as all comparable sales also use similar systems. No public water or sewer hookups are available in this area.",
    },
    {
      q: "What does the FEMA flood zone designation mean?",
      a: "The property is located in FEMA Flood Zone X, which is outside the Special Flood Hazard Area (SFHA). This means the property has a minimal risk of flooding and federal flood insurance is not required for mortgage purposes. The flood map reference is 16051C1634C, dated September 26, 2008.",
    },
  ],

  // ── Narrative Addenda ─────────────────────────────────────────────────────
  narrative: {
    adjustmentSummary: "A $50/sf adjustment was given for GLA; a $50/sf adjustment was given for basement area. No site adjustments were made due to paired sales analysis showing no adjustments were warranted. No adjustments denote 'no market difference.' Adjustments for minor amenities and room counts were not warranted as they could not be supported in the limited market. A dollar-for-dollar adjustment was given for concessions as this accurately describes a negative reflection in the sales value.",
    highestAndBestUse: "The subject's highest and best use as improved is its current use as a single-family residence. This was determined using the four tests of Highest and Best Use: (1) Physically Possible — the current use is physically possible as it is currently being used as such; (2) Legally Permissible — local zoning was researched and the current use is legal; (3) Financially Feasible — the current use is financially feasible as it is currently being used as such and has a history of current use; (4) Highest Value — all other viable uses were looked at and it appears that the highest value is current use.",
    scopeOfWork: "The property was measured using ANSI Standards where possible (measurements rounded to the nearest half-foot) and a sketch is attached. Each major room was inspected in the interior of the subject and their general placement was noted on the attached sketch. The county treasurer's office was contacted through computer and/or telephone and the parcel number, short legal description, tax information, lot size, and age of the subject was obtained or verified through public records. Photos were taken of the subject's street, front, rear, living area, kitchen, and bathrooms.",
    limitingConditions: "This appraisal is completed with the extraordinary assumption that the subject has no adverse issues (unless stated otherwise) such as lead-based paint, mold, etc. The appraiser is not a home inspector, and this appraisal report is not a home inspection report. It does not guarantee or imply that the property or any structures are free of defects or property condition problems. The appraiser has not identified any purchaser, borrower, or seller as an intended user of this appraisal.",
    reconciliation: "Final reconciliation was found by weighting the adjusted comparables. The Sales Comparison Approach was given primary weight as it most directly reflects market behavior. The Cost Approach was given secondary weight as a reasonableness check. The Income Approach was not developed as the subject is owner-occupied and not typically rented in this market. The final value opinion of $664,000 as of April 22, 2026 represents the most probable price that the property would bring in a competitive and open market.",
  },
};

export type ReportData = typeof reportData;
export type Comparable = typeof reportData.comparables[0];
